(uiop/package:define-package :sample-pixijs-on-cl/main 
  (:nicknames :sample-pixijs-on-cl)
  (:use-reexport :sample-pixijs-on-cl/server)
  (:import-from :sample-pixijs-on-cl/sample/simple)
  (:import-from :sample-pixijs-on-cl/sample/container)
  (:import-from :sample-pixijs-on-cl/sample/many-objects)
  (:import-from :sample-pixijs-on-cl/sample/text)
  (:import-from :sample-pixijs-on-cl/sample/texture)
  (:import-from :sample-pixijs-on-cl/sample/z-index))
